before:
  hooks:
    - go mod download

builds:
- id: entrello
  main: ./cmd/
  binary: entrello
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  goarm: [6, 7]

archives:
- id: entrello-archive
  name_template: |-
    entrello_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    {{- with .Arm -}}
      {{- if (eq . "6") -}}hf
      {{- else -}}v{{- . -}}
      {{- end -}}
    {{- end -}}
  builds:
    - entrello
  replacements:
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files: ["LICENSE"]

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
