api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
api_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
board_id: xxxxxxxxxxxxxxxxxxxxxxxx
list_id: xxxxxxxxxxxxxxxxxxxxxxxx

sources:
  github_issues:
    enabled: true
    period:
      type: minute
      interval: 15
    personal_access_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    label_id: xxxxxxxxxxxxxxxxxxxxxxxx

  tododock:
    enabled: true
    period:
      type: hour
      interval: 1
    email: abc@def.com
    password: xxxxxxxx
    label_id: xxxxxxxxxxxxxxxxxxxxxxxx
