timezone_location: Europe/Istanbul
timeout_secs: 45

trello:
  api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  api_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  board_id: xxxxxxxxxxxxxxxxxxxxxxxx
  todo_list_id: xxxxxxxxxxxxxxxxxxxxxxxx
  today_list_id: xxxxxxxxxxxxxxxxxxxxxxxx

telegram:
  enabled: true
  token: xxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  chat_id: 1234567890

sources:
  github_issues:
    personal_access_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    source_config:
      name: "Github Issues"
      enabled: true
      strict: true
      label_id: xxxxxxxxxxxxxxxxxxxxxxxx
      period:
        type: minute
        interval: 15

  tododock:
    email: abc@def.com
    password: xxxxxxxx
    source_config:
      name: "TodoDock"
      enabled: true
      strict: false
      label_id: xxxxxxxxxxxxxxxxxxxxxxxx
      period:
        type: hour
        interval: 1

  habits:
    spreadsheet_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    credentials_file: credentials.json
    token_file: token.json
    source_config:
      name: "Google Spreadsheet Habits"
      enabled: true
      strict: true
      label_id: xxxxxxxxxxxxxxxxxxxxxxxx
      period:
        type: hour
        interval: 12
