timeout_secs: 45

trello:
  api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  api_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  board_id: xxxxxxxxxxxxxxxxxxxxxxxx
  list_id: xxxxxxxxxxxxxxxxxxxxxxxx

sources:
  github_issues:
    enabled: true
    strict: true
    period:
      type: minute
      interval: 15
    personal_access_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    label_id: xxxxxxxxxxxxxxxxxxxxxxxx

  tododock:
    enabled: true
    strict: false
    period:
      type: hour
      interval: 1
    email: abc@def.com
    password: xxxxxxxx
    label_id: xxxxxxxxxxxxxxxxxxxxxxxx

  habits:
    enabled: true
    strict: true
    period:
      type: hour
      interval: 12

telegram:
  enabled: true
  token: xxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  chat_id: 1234567890
