timezone_location: Europe/Istanbul
timeout_secs: 45

trello:
  api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  api_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  board_id: xxxxxxxxxxxxxxxxxxxxxxxx
  todo_list_id: xxxxxxxxxxxxxxxxxxxxxxxx
  today_list_id: xxxxxxxxxxxxxxxxxxxxxxxx

telegram:
  enabled: true
  token: xxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  chat_id: 1234567890

sources:
  github_issues:
    name: "Github Issues"
    endpoint: https://<domain>:<port>/entrello
    enabled: true
    strict: true
    label_id: xxxxxxxxxxxxxxxxxxxxxxxx
    period:
      type: minute
      interval: 15

  tododock:
    name: "TodoDock"
    endpoint: https://<domain>:<port>/entrello
    enabled: true
    strict: false
    label_id: xxxxxxxxxxxxxxxxxxxxxxxx
    period:
      type: hour
      interval: 1

  habits:
    name: "Google Spreadsheet Habits"
    endpoint: https://<domain>:<port>/entrello
    enabled: true
    strict: true
    label_id: xxxxxxxxxxxxxxxxxxxxxxxx
    period:
      type: hour
      interval: 12
